// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWHJ6iH3t4CTK_lBd8MKQryP74txXuLrk',
    appId: '1:485144283263:web:d4c5856f9a4841a917d74a',
    messagingSenderId: '485144283263',
    projectId: 'chat-app-2b4da',
    authDomain: 'chat-app-2b4da.firebaseapp.com',
    storageBucket: 'chat-app-2b4da.firebasestorage.app',
    measurementId: 'G-W3MYT8F6RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOIQuRvO24z7iwvQ64NxHAZhSy4yaEhn0',
    appId: '1:485144283263:android:0ea9e6c8d8e4ab6617d74a',
    messagingSenderId: '485144283263',
    projectId: 'chat-app-2b4da',
    storageBucket: 'chat-app-2b4da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnc6BRmgPIuzTkOAJkh6G5vGogorqVRlI',
    appId: '1:485144283263:ios:f5aab90daf7398c017d74a',
    messagingSenderId: '485144283263',
    projectId: 'chat-app-2b4da',
    storageBucket: 'chat-app-2b4da.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnc6BRmgPIuzTkOAJkh6G5vGogorqVRlI',
    appId: '1:485144283263:ios:f5aab90daf7398c017d74a',
    messagingSenderId: '485144283263',
    projectId: 'chat-app-2b4da',
    storageBucket: 'chat-app-2b4da.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWHJ6iH3t4CTK_lBd8MKQryP74txXuLrk',
    appId: '1:485144283263:web:2a2cb6cf5b6f7fc917d74a',
    messagingSenderId: '485144283263',
    projectId: 'chat-app-2b4da',
    authDomain: 'chat-app-2b4da.firebaseapp.com',
    storageBucket: 'chat-app-2b4da.firebasestorage.app',
    measurementId: 'G-3DWPDL41XJ',
  );
}
